-- 主表
CREATE TABLE `$basic_table` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `catid` smallint(5) unsigned NOT NULL default '0',
  `title` char(80) NOT NULL default '',
  `style` char(100) NOT NULL default '',
  `thumb` char(100) NOT NULL default '',
  `keywords` char(100) NOT NULL default '',
  `description` char(255) NOT NULL default '',
  `tags` char(100) NOT NULL default '',
  `posids` tinyint(1) unsigned NOT NULL default '0',
  `sort` tinyint(3) unsigned NOT NULL default '0',
  `status` tinyint(2) unsigned NOT NULL default '1',
  `islink` tinyint(1) unsigned NOT NULL default '0',
  `is_deleted` tinyint(1) unsigned NOT NULL default '0',
  `username` char(20) NOT NULL,
  `author` char(20) NOT NULL,
  `views` int(10) unsigned NOT NULL default '0',
  `update_at` int(10) unsigned NOT NULL default '0',
  `create_at` int(10) unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`),
  KEY `status` (`status`,`sort`,`id`),
  KEY `listorder` (`catid`,`status`,`sort`,`id`),
  KEY `catid` (`catid`,`status`,`id`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_bin;

-- 从表

INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'catid', '栏目', '', '', '1', '6', '/^[0-9]{1,6}$/', '请选择栏目', 'catid', 'array (\n  \'defaultvalue\' => \'\',\n)', '', '0', '0', '1', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'title', '标题', '', 'layui-input', '1', '80', '', '请输入标题', 'title', '', '', '0', '0', '1', '0', '1', '1', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'thumb', '缩略图', '', '', '0', '100', '', '', 'image', 'array (\n  \'size\' => \'50\',\n  \'defaultvalue\' => \'\',\n  \'show_type\' => \'1\',\n  \'upload_maxsize\' => \'1024\',\n  \'upload_allowext\' => \'jpg|jpeg|gif|png|bmp\',\n  \'watermark\' => \'0\',\n  \'isselectimage\' => \'1\',\n  \'images_width\' => \'\',\n  \'images_height\' => \'\',\n)', '', '0', '0', '1', '0', '0', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'keywords', '关键词', '多关键词之间用空格或者“,”隔开', '', '0', '40', '', '', 'keyword', 'array (\r\n  \'size\' => \'100\',\r\n  \'defaultvalue\' => \'\',\r\n)', '', '0', '0', '1', '0', '1', '1', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'description', '摘要', '', '', '0', '255', '', '', 'textarea', 'array (\r\n  \'width\' => \'98\',\r\n  \'height\' => \'46\',\r\n  \'defaultvalue\' => \'\',\r\n  \'enablehtml\' => \'0\',\r\n)', '', '0', '0', '1', '0', '1', '1', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'update_at', '更新时间', '', '', '0', '0', '', '', 'datetime', 'array (\r\n  \'dateformat\' => \'int\',\r\n  \'format\' => \'Y-m-d H:i:s\',\r\n  \'defaulttype\' => \'1\',\r\n  \'defaultvalue\' => \'\',\r\n)', '', '1', '0', '1', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'content', '内容', '<div class=\"content_attr\"><label><input name=\"add_introduce\" type=\"checkbox\"  value=\"1\" checked>是否截取内容</label><input type=\"text\" name=\"introcude_length\" value=\"200\" size=\"3\">字符至内容摘要\r\n<label><input type=\'checkbox\' name=\'auto_thumb\' value=\"1\" checked>是否获取内容第</label><input type=\"text\" name=\"auto_thumb_no\" value=\"1\" size=\"2\" class=\"\">张图片作为标题图片\r\n</div>', '', '1', '999999', '', '内容不能为空', 'editor', 'array (\n  \'toolbar\' => \'full\',\n  \'defaultvalue\' => \'\',\n  \'enablekeylink\' => \'1\',\n  \'replacenum\' => \'2\',\n  \'link_mode\' => \'0\',\n  \'enablesaveimage\' => \'1\',\n)', '', '0', '0', '0', '0', '1', '1', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'pages', '分页方式', '', '', '0', '0', '', '', 'pages', '', '', '0', '0', '0', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'create_at', '发布时间', '', '', '0', '0', '', '', 'datetime', 'array (\n  \'fieldtype\' => \'int\',\n  \'format\' => \'Y-m-d H:i:s\',\n  \'defaulttype\' => \'0\',\n)', '', '0', '0', '1', '0', '0', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'posids', '推荐位', '', '', '0', '0', '', '', 'posid', 'array (\n  \'cols\' => \'4\',\n  \'width\' => \'125\',\n)', '', '0', '0', '1', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'url', 'URL', '', '', '0', '100', '', '', 'text', '', '', '1', '0', '1', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'views', '', '', '', '0', '0', '', '', 'number', '', '', '0', '0', '1', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'sort', '排序', '', '', '0', '6', '', '', 'number', '', '', '1', '0', '1', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'status', '状态', '', '', '0', '2', '', '', 'box', '', '', '1', '0', '1', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'relation', '相关文章', '', '', '0', '0', '', '', 'omnipotent', 'array (\n  \'formtext\' => \'<input type=\\\'hidden\\\' name=\\\'info[relation]\\\' id=\\\'relation\\\' value=\\\'{FIELD_VALUE}\\\' style=\\\'50\\\' >\r\n<ul class=\"list-dot\" id=\"relation_text\"></ul>\r\n<div>\r\n<input type=\\\'button\\\' value=\"添加相关\" onclick=\"omnipotent(\\\'selectid\\\',\\\'?m=content&c=content&a=public_relationlist&modelid={MODELID}\\\',\\\'添加相关文章\\\',1)\" class=\"button\" style=\"width:66px;\">\r\n<span class=\"edit_content\">\r\n<input type=\\\'button\\\' value=\"显示已有\" onclick=\"show_relation({MODELID},{ID})\" class=\"button\" style=\"width:66px;\">\r\n</span>\r\n</div>\',\n  \'fieldtype\' => \'varchar\',\n  \'minnumber\' => \'1\',\n)', '', '0', '0', '0', '0', '0', '1', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'copyfrom', '来源', '', '', '0', '100', '', '', 'copyfrom', 'array (\n  \'defaultvalue\' => \'\',\n)', '', '0', '0', '0', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'islink', '转向链接', '', '', '0', '0', '', '', 'islink', '', '', '0', '0', '1', '0', '0', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'username', '文章发布者', '', '', '0', '20', '', '', 'text', '', '', '1', '0', '1', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'tags', '标签', '多标签之间用空格或者“,”隔开', '', '0', '0', '', '', 'text', '', '', '0', '0', '1', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'author', '文章作者', '', '', '0', '0', '', '', 'text', '', '', '0', '0', '1', '0', '1', '0', '0', '0');
INSERT INTO `$table_model_field` (`modelid`, `field`, `name`, `tips`, `css`, `minlength`, `maxlength`, `pattern`, `errortips`, `formtype`, `setting`, `formattribute`, `iscore`, `isindex`, `issystem`, `isunique`, `isbase`, `issearch`, `sort`, `disabled`) VALUES ($modelid, 'is_deleted', '是否标记为删除', '', '', '0', '0', '', '', 'box', '', '', '0', '0', '1', '0', '0', '0', '0', '0');
