<?php
namespace app\cms\service;
use think\admin\Service;

/**
 * 模型字段服务类
 * Class FieldService
 */
class FieldService extends Service
{
    /**
     * 创建主表
     */
    public function CreateMainTable($tablename)
    {
        $sql = "CREATE TABLE `".$tablename."` (
              `id` mediumint(8) unsigned NOT NULL auto_increment,
              `catid` smallint(5) unsigned NOT NULL default '0',
              `title` char(80) NOT NULL default '',
              `style` char(100) NOT NULL default '',
              `thumb` char(100) NOT NULL default '',
              `keywords` char(100) NOT NULL default '',
              `description` char(255) NOT NULL default '',
              `tags` char(100) NOT NULL default '',
              `posids` tinyint(1) unsigned NOT NULL default '0',
              `sort` tinyint(3) unsigned NOT NULL default '0',
              `status` tinyint(2) unsigned NOT NULL default '1',
              `islink` tinyint(1) unsigned NOT NULL default '0',
              `is_deleted` tinyint(1) unsigned NOT NULL default '0',
              `username` char(20) NOT NULL,
              `author` char(20) NOT NULL,
              `views` int(10) unsigned NOT NULL default '0',
              `update_at` int(10) unsigned NOT NULL default '0',
              `create_at` int(10) unsigned NOT NULL default '0',
              PRIMARY KEY  (`id`),
              KEY `status` (`status`,`sort`,`id`),
              KEY `listorder` (`catid`,`status`,`sort`,`id`),
              KEY `catid` (`catid`,`status`,`id`)
            )
            ENGINE=InnoDB
            DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_bin;";
        return $this->app->db->query($sql);
    }

    /**
     * 创建附属表
     */
    public function CreateSubTable($tablename)
    {
        $sql = 'CREATE TABLE `'.$tablename.'` (`id` mediumint(8) NOT NULL ,`content` text NOT NULL COMMENT "内容") ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_bin;';
        return $this->app->db->query($sql);
    }

    /**
     * 初始化一个模型的默认字段
     */
    public function InitModelField($modelid)
    {
        $initField = [
            [
                'modelid' => $modelid,
                'field' => 'catid',
                'name' => '栏目',
                'tips' => '',
                'css' => '',
                'minlength' => '1',
                'maxlength' => '6',
                'pattern' => '/^[0-9]{1,6}$/',
                'errortips' => '请选择栏目',
                'formtype' => 'catid',
                'setting' => json_encode(['defaultvalue'=>'']),
                'formattribute' => '',
                'sort' => 1,
                'iscore' => 1,
                'isindex' => 1,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 1,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'title',
                'name' => '文章标题',
                'tips' => '请输入文章标题',
                'css' => '',
                'minlength' => '1',
                'maxlength' => '80',
                'pattern' => '',
                'errortips' => '请输入文章标题',
                'formtype' => 'title',
                'setting' => '',
                'formattribute' => '',
                'sort' => 2,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 1,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'keywords',
                'name' => '文章关键字',
                'tips' => '请输入文章关键字',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '150',
                'pattern' => '',
                'errortips' => '请输入文章关键字',
                'formtype' => 'keywords',
                'setting' => json_encode(['size' => '100', 'defaultvalue' => '']),
                'formattribute' => '',
                'sort' => 3,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'tags',
                'name' => '文章标签',
                'tips' => '请输入文章标签',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '150',
                'pattern' => '',
                'errortips' => '请输入文章标签',
                'formtype' => 'tags',
                'setting' => json_encode(['size' => '100', 'defaultvalue' => '']),
                'formattribute' => '',
                'sort' => 4,
                'iscore' => 0,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'description',
                'name' => '文章摘要',
                'tips' => '请输入文章摘要',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '255',
                'pattern' => '',
                'errortips' => '请输入文章摘要',
                'formtype' => 'title',
                'setting' => json_encode(['width' => '98', 'height' => '46', 'defaultvalue' => '', 'enablehtml' => '0']),
                'formattribute' => '',
                'sort' => 5,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'conent',
                'name' => '内容',
                'tips' => '请输入文章内容',
                'css' => '',
                'minlength' => '1',
                'maxlength' => '999999',
                'pattern' => '',
                'errortips' => '文章内容不能为空',
                'formtype' => 'editor',
                'setting' => json_encode(['toolbar' => 'full', 'defaultvalue' => '', 'enablekeylink' => '1', 'replacenum' => '2', 'link_mode' => '0', 'enablesaveimage' => '1']),
                'formattribute' => '',
                'sort' => 6,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 1,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'pages',
                'name' => '文章分页方式',
                'tips' => '<div class="content_attr"><label><input name="add_introduce" type="checkbox"  value="1" checked>是否截取内容</label><input type="text" name="introcude_length" value="200" size="3">字符至内容摘要
<label><input type="checkbox" name="auto_thumb" value="1" checked>是否获取内容第</label><input type="text" name="auto_thumb_no" value="1" size="2" class="">张图片作为标题图片
</div>',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '80',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'pages',
                'setting' => '',
                'formattribute' => '',
                'sort' => 7,
                'iscore' => 0,
                'isindex' => 0,
                'issystem' => 0,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'posids',
                'name' => '推荐位',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '80',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'posid',
                'setting' => '',
                'formattribute' => 'checkbox',
                'sort' => 8,
                'iscore' => 0,
                'isindex' => 0,
                'issystem' => 0,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'thumb',
                'name' => '文章缩略图',
                'tips' => '请上传文章缩略图',
                'css' => '',
                'minlength' => '1',
                'maxlength' => '100',
                'pattern' => '',
                'errortips' => '请上传文章缩略图',
                'formtype' => 'image',
                'setting' => json_encode(['size' => '50',
                    'defaultvalue' => '',
                    'show_type' => '1',
                    'upload_maxsize' => '1024',
                    'upload_allowext' => 'jpg|jpeg|gif|png|bmp',
                    'watermark' => '0',
                    'isselectimage' => '1',
                    'images_width' => '',
                    'images_height' => '']),
                'formattribute' => '',
                'sort' => 9,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 0,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'views',
                'name' => '点击量',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '10',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'islink',
                'setting' => '',
                'formattribute' => '',
                'sort' => 10,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'copyfrom',
                'name' => '文章来源',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '100',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'copyfrom',
                'setting' => json_encode(['defaultvalue' => '']),
                'formattribute' => '',
                'sort' => 11,
                'iscore' => 0,
                'isindex' => 0,
                'issystem' => 0,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'username',
                'name' => '文章发布者',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '20',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'text',
                'setting' => '',
                'formattribute' => '',
                'sort' => 12,
                'iscore' => 0,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'author',
                'name' => '文章作者',
                'tips' => '页面展示的文章作者',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '20',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'text',
                'setting' => '',
                'formattribute' => '',
                'sort' => 13,
                'iscore' => 0,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'islink',
                'name' => '转向链接',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '0',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'islink',
                'setting' => '',
                'formattribute' => '',
                'sort' => 14,
                'iscore' => 0,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'status',
                'name' => '文章状态',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '10',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'box',
                'setting' => '',
                'formattribute' => '',
                'sort' => 15,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'sort',
                'name' => '文章排序',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '6',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'number',
                'setting' => '',
                'formattribute' => '',
                'sort' => 16,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'is_deleted',
                'name' => '是否标记为删除',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '1',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'radio',
                'setting' => '',
                'formattribute' => '',
                'sort' => 17,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'relation',
                'name' => '相关文章',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '0',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'omnipotent',
                'setting' => '',
                'formattribute' => '',
                'sort' => 18,
                'iscore' => 0,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'create_at',
                'name' => '文章创建时间',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '10',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'datetime',
                'setting' => '',
                'formattribute' => '',
                'sort' => 19,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
            [
                'modelid' => $modelid,
                'field' => 'update_at',
                'name' => '文章更新时间',
                'tips' => '',
                'css' => '',
                'minlength' => '0',
                'maxlength' => '10',
                'pattern' => '',
                'errortips' => '',
                'formtype' => 'datetime',
                'setting' => '',
                'formattribute' => '',
                'sort' => 20,
                'iscore' => 1,
                'isindex' => 0,
                'issystem' => 1,
                'isunique' => 0,
                'isbase' => 1,
                'issearch' => 0,
                'disabled' => 0
            ],
        ];
        return $this->app->db->name('cms_model_field')->insertAll($initField);
    }
}